### ISSUE TITLE
Love what you have done thus far---

### ISSUE THREAD

**Issue by DrDrache** [EdwardChamberlain/IPMI-Fan-Controller#6]
Love what you have done thus far - works well.
as for further enhancements; I really don't know if this will help you AT ALL... so please forgive me if it's only useful as information.

https://github.com/spacelama/Scripts/tree/master/R710-IPMI-TEMP

this is an "older" perl based script that does quite a bit of automation for the IPMI control of fans with dell IDRAC.

feel free to close this whenever; just the only way I thought of giving the info.

**Comment by EdwardChamberlain** [comment]
Thanks! Thats quite useful. There are a number of similar scripts floating around out there. 

I hope to get back into developing this shortly but unfortunately my T320 which I used as a test platform is in storage at the moment following a house move! Once I have that machine up and running again I plan on updating this container with temp monitoring and some other IPMI tools. If theres anything specific you would like adding please let me know!
