### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by DOHCDragon** [EdwardChamberlain/IPMI-Fan-Controller#7]
had a power outage.. after wards i get:

"Error: Unable to establish IPMI v2 / RMCP+ session"

every time I try to turn on "enable manual control" I feel like I'm missing something stupid easy. I verified that IPMI is enabled and I can manually login to the idrac. I can also ssh into it. This docker worked very well and I would love to figure out how to put the developer version on for automatic fan speeds but atm I just want it to go back to working. if anyone can help it would be great.

**Comment by Burning-Beard** [comment]
Have you had any success connecting?  I am running into the same issue.  I tried manually connecting through console and I get the same "Error: Unable to establish IPMI v2 / RMCP+ session"

**Comment by Burning-Beard** [comment]
I had the same issue.  I ended up removing/disabling ipmitools in nerdpack and removed the docker.  Rebooted and reinstalled /enabled ipmitools and docker. 
Seems to be working again.
